### ISSUE TITLE
error window disable autoclose?

### ISSUE THREAD

**Issue by raghuramos1987** [okcompute/vim-nose#3]
the error window closes before i can read the error (or success).

**Comment by okcompute** [comment]
Hi, this was fixed in issue #2. Can you tell me which platform you are using? Linux? Windows?

**Comment by ereOn** [comment]
Note that the fact the windows disappear in case of success is actually desirable.

The output in such cases is rarely (or : never) informative so it makes no sense to show it anyway.

**Comment by raghuramos1987** [comment]
on error too. I'm on linux (centos). And, it works with RunTest! but not with RunTest. you're right, i dont need it to show it on success.

**Comment by raghuramos1987** [comment]
closing this. i'm unable to reproduce. on a new install.
